### ISSUE TITLE
ArithmethicException when JobInfo contains no messages

### ISSUE THREAD

**Issue by christopherkeil0689** [otto-de/edison-microservice#128]
Since edison 2.2.10, job messages cleanup code causes an error if a job is not logging any messages. This leads to an empty `messages` array for entries in the `jobInfo` MongoDB collection which is currently used to calculate average message size in the following line:

`int averageMessageSize = bsonSize / jobInfo.getMessages().size();`

A job without logs will produce a divide-by-zero scenario. Here is an example stacktrace:

`java.lang.ArithmeticException: / by zero
	at de.otto.edison.jobs.repository.mongo.MongoJobRepository.keepJobMessagesWithinMaximumSize(MongoJobRepository.java:287)
	at de.otto.edison.jobs.service.JobService.lambda$handleTooBigJobLogs$8(JobService.java:269)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at de.otto.edison.jobs.service.JobService.handleTooBigJobLogs(JobService.java:267)
	at de.otto.edison.jobs.repository.cleanup.CleanupMessagesOfTooBigJobLogs.doCleanUp(CleanupMessagesOfTooBigJobLogs.java:23)
	at jdk.internal.reflect.GeneratedMethodAccessor154.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)`

**Comment by MediaMarco** [comment]
Fixed, will be part of next release. Thank you!

**Comment by MediaMarco** [comment]
Fixed in 2.4.2
