### ISSUE TITLE
Errors with RC5

### ISSUE THREAD

**Issue by cfinckler** [otto-de/edison-microservice#61]
Hello, with upgrade to RC4 we get the following exception during the start of a job:
`com.mongodb.MongoCommandException: Command failed with error 11000: 'E11000 duplicate key error collection: composing.jobmeta index: _id_ dup key: { : "GenerateNewestCompositionImageJob" }' on server db-live-460925.lhotse.ov.otto.de:27017. The full response is { "ok" : 0.0, "errmsg" : "E11000 duplicate key error collection: composing.jobmeta index: _id_ dup key: { : \"GenerateNewestCompositionImageJob\" }", "code" : 11000 }
	at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:115)
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:114)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:173)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:215)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:152)
	at com.mongodb.operation.FindAndUpdateOperation$1.call(FindAndUpdateOperation.java:305)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:230)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:221)
	at com.mongodb.operation.FindAndUpdateOperation.execute(FindAndUpdateOperation.java:302)
	at com.mongodb.Mongo.execute(Mongo.java:781)
	at com.mongodb.Mongo$2.execute(Mongo.java:764)
	at com.mongodb.MongoCollectionImpl.findOneAndUpdate(MongoCollectionImpl.java:407)
	at de.otto.edison.mongo.jobs.MongoJobMetaRepository.createValue(MongoJobMetaRepository.java:141)
	at de.otto.edison.mongo.jobs.MongoJobMetaRepository.setRunningJob(MongoJobMetaRepository.java:70)
	at de.otto.edison.jobs.service.JobMetaService.aquireRunLock(JobMetaService.java:55)
	at de.otto.edison.jobs.service.JobService.startAsyncJob(JobService.java:101)
	at de.otto.social.composing.common.job.JobWatcher.lambda$registerCronJob$3(JobWatcher.java:41)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Unexpected error occurred in scheduled task.`

Ob das Problem nur auftritt, wenn bereits alte Jobs von vor dem Release in der DB existieren, weiß ich nicht. Hab jetzt erstmal downgegradet.

**Comment by gsteinacker** [comment]
MongoJobMetaRepository.createValue() fängt DuplicateKeyExceptions und behandelt sie augenscheinlich korrekt. Ohne etwas mehr Kontext (z.B. einen Test, der das o.g. Verhalten zeigt) kann ich das nicht nachvollziehen. Ich schließe den Bug daher erstmal.
