### ISSUE TITLE
SAXParseException when requesting /internal/loggers

### ISSUE THREAD

**Issue by jbaudisc** [otto-de/edison-microservice#93]
When requesting the endpoint /internal/loggers, the following Exception is thrown:

```
Caused by: org.thymeleaf.exceptions.TemplateInputException: Exception parsing document: template="loggers", line 38 - column 73
at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplateUsingPool(AbstractNonValidatingSAXTemplateParser.java:166)
at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplate(AbstractNonValidatingSAXTemplateParser.java:116)
at org.thymeleaf.TemplateRepository.getTemplate(TemplateRepository.java:278)
at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1104)
at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1060)
at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1011)
at org.thymeleaf.spring4.view.ThymeleafView.renderFragment(ThymeleafView.java:335)
at org.thymeleaf.spring4.view.ThymeleafView.render(ThymeleafView.java:190)
at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1282)
at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
... 60 common frames omitted
Caused by: org.xml.sax.SAXParseException: Attribute name "hidden" associated with an element type "input" must be followed by the ' = ' character.
at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
```

The problem is that file loggers.html is not XHTML - conform in line 38:

`<input type="hidden" hidden name="name" th:value="${logger.name}">`

Workaround: update to Thymeleaf 3.0.6 including following dependencies:
```
'org.thymeleaf:thymeleaf:3.0.6.RELEASE',
'org.thymeleaf:thymeleaf-spring4:3.0.6.RELEASE',
'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:2.1.0'
```

**Comment by gsteinacker** [comment]
Kannst du einen Fix bereitstellen?

**Comment by jbaudisc** [comment]
Dieser Pull-Request fixt den Bug:
https://github.com/otto-de/edison-microservice/pull/95
